#%RAML 1.0
title: max150

types:
  AmericanFlights: !include 

/flights:
  post:
      
  get:
      queryParameters:
        destination:
          required: false
          enum:
            - SFO
            - LAX
            - CLE
  /{ID}:
    get:
        