#%RAML 1.0
title: max150

types:
  AmericanFlight: !include 

/flights:
  post:
      
  get:
      queryParameters:
        destination:
          required: false
          enum:
            - SFO
            - LAX
            - CLE
      responses:
        200:
          body:
            application/json:
              type: AmericanFlight[]
              examples:
                output: !include 
  /{ID}:
    get:

        